image: node:20-alpine

stages:
  - setup
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/
    - node_modules/.cache/turbo/

# 2. Установка зависимостей
install_dependencies:
  stage: setup
  script:
    - npm ci

# 3. Сборка проекта (Turborepo сделает это быстро)
build_apps:
  stage: build
  script:
    - npx turbo run build
  artifacts:
    paths:
      # Сохраняем собранные файлы, чтобы передать их на следующий этап
      - apps/supply/dist/
      - apps/finance/dist/
      - apps/distribution/dist/
    expire_in: 1 day # Храним артефакты 1 день в GitLab

# 4. Деплой на твой VPS по SSH
deploy_to_vps:
  stage: deploy
  only:
    - master # Деплоим только при пуше в ветку main
  before_script:
    # Настраиваем SSH для доступа к твоему VPS
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
  script:
    # Копируем собранные файлы на твой сервер
    - rsync -avz --delete apps/supply/dist/ $VPS_USER@$VPS_IP:/var/www/supply/
    - rsync -avz --delete apps/finance/dist/ $VPS_USER@$VPS_IP:/var/www/finance/
