services:
  supply:
    image: ghcr.io/${APP_REPO}/supply:${SUPPLY_VERSION}
    ports:
      - '127.0.0.1:8001:80'
    restart: always

  distribution:
    image: ghcr.io/${APP_REPO}/distribution:${DISTRIBUTION_VERSION}
    ports:
      - '127.0.0.1:8002:80'
    restart: always

  finance:
    image: ghcr.io/${APP_REPO}/finance:${FINANCE_VERSION}
    ports:
      - '127.0.0.1:8003:80'
    restart: always

  storybook:
    image: ghcr.io/${APP_REPO}/storybook:${STORYBOOK_VERSION}
    ports:
      - '127.0.0.1:8003:6006'
    restart: always
