# Память она такая, время от времени кончается
name: Cleanup Old GHCR Images

on:
  schedule:
    # Запускать автоматически каждое воскресенье в 3:00 ночи пока я сплю
    - cron: '0 3 * * 0'

  # Оставляем возможность запустить очистку вручную по кнопке
  workflow_dispatch:

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest

    # Важно: Нужно дать разрешение экшену удалять пакеты
    permissions:
      packages: write
      contents: read

    strategy:
      # Вот этот шаг нужно запустить для каждого пакета
      matrix:
        package:
          - 'mrv-erp/distribution'
          - 'mrv-erp/finance'
          - 'mrv-erp/supply'

    steps:
      - name: Cleanup ${{ matrix.package }}
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package }}
          package-type: 'container'
          # Резервирую 5 версий на случай если придется откатить билд
          min-versions-to-keep: 5
          # Если раскомментировать, то можно будет удалять только "осиротевшие" сборки без тегов
          # delete-only-untagged-versions: 'true'
