name: Deploy

on:
  push:
    branches:
      - dev
  # Продакшен деплоим ТОЛЬКО когда успешно отработал воркфлоу релиза (Lerna)
  workflow_run:
    workflows: ['Release']
    types:
      - completed
    branches:
      - master
  # Зарезервировал триггер запуска если кончатся лимиты времени выполнения бесплатного ранера в github.
  # Тогда можно будет выбрать "self-hosted" и запустится раннер развернутый на том же сервере, на котором крутится приложение
  # Это немного медленнее, но скорость доставки в проекте не является сверхкритичным фактором
  # Возможно есть способ настроить проверку лимитов и автоматизировать выбор ранера, но пока - YAGNI
  workflow_dispatch:
    inputs:
      runner_env:
        description: 'Где выполнять сборку?'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - self-hosted

jobs:
  # Анализ изменений в коде
  # Поскольку в монорепозитории находится три сервиса, то будет тупо постоянно всех их деплоить заново
  # поэтому включаем анализ был затронут пакет или нет для каждого приложения. И на основе эти данных будет приниматься решение
  # запускать деплой или нет (через поднятие версии хеша комита у каждого приложения в docker-compose.yml)
  changes:
    # Запускаем только если воркфлоу релиза завершился успешно или это ручной запуск / пуш в dev
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    runs-on: ubuntu-latest
    outputs:
      supply: ${{ steps.filter.outputs.supply }}
      distribution: ${{ steps.filter.outputs.distribution }}
      finance: ${{ steps.filter.outputs.finance }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            supply:
            - 'apps/supply/**'
            - 'packages/**'
            distribution:
            - 'apps/distribution/**'
            - 'packages/**'
            finance:
            - 'apps/finance/**'
            - 'packages/**'

  # Сборка образов
  build-and-push:
    needs: changes
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    runs-on: ${{ github.event.inputs.runner_env || 'ubuntu-latest' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set global vars
        run: |
          echo "REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      # Supply (ТОЛЬКО если он изменился ИЛИ запуск ручной)
      - name: Build and Push Supply
        if: needs.changes.outputs.supply == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          docker build --build-arg APP_DIR=supply --build-arg APP_SCOPE=@mrv-erp/supply -t ghcr.io/$REPO/supply:$TAG -f ./Dockerfile .
          docker push ghcr.io/$REPO/supply:$TAG

      # Distribution
      - name: Build and Push Distribution
        if: needs.changes.outputs.distribution == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          docker build --build-arg APP_DIR=distribution --build-arg APP_SCOPE=@mrv-erp/distribution -t ghcr.io/$REPO/distribution:$TAG -f ./Dockerfile .
          docker push ghcr.io/$REPO/distribution:$TAG

      # Finance
      - name: Build and Push Finance
        if: needs.changes.outputs.finance == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          docker build --build-arg APP_DIR=finance --build-arg APP_SCOPE=@mrv-erp/finance -t ghcr.io/$REPO/finance:$TAG -f ./Dockerfile .
          docker push ghcr.io/$REPO/finance:$TAG

  # Деплой
  deploy:
    needs: [changes, build-and-push]
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}

    # Если ветка триггера (из workflow_run) master или текущий ref master — окружение production. Иначе — staging
    environment: ${{ (github.event.workflow_run.head_branch == 'master' || github.ref == 'refs/heads/master') && 'production' || 'staging' }}

    runs-on: ${{ github.event.inputs.runner_env || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'docker-compose.yml'
          target: '~/mrv-erp'

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          TAG: ${{ github.sha }}
          REPO: ${{ github.repository }}
          DOMAIN: ${{ vars.DOMAIN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          # Передаем токен и имя аккаунта для авторизации докера в ghrc перед получением образов
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACTOR: ${{ github.actor }}
          # Передача признаков изменения того или иного приложения
          UPDATE_SUPPLY: ${{ needs.changes.outputs.supply }}
          UPDATE_DIST: ${{ needs.changes.outputs.distribution }}
          UPDATE_FINANCE: ${{ needs.changes.outputs.finance }}
          IS_MANUAL: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: TAG, REPO, DOMAIN, DB_PASSWORD, GH_TOKEN, GH_ACTOR, UPDATE_SUPPLY, UPDATE_DIST, UPDATE_FINANCE, IS_MANUAL
          script: |
            echo "$GH_TOKEN" | docker login ghcr.io -u "$GH_ACTOR" --password-stdin
            # Надо перейти в папку в которую scp-action положил docker-compose.yml
            # Когда запустится docker compose pull он будет искать docker-compose.yml в папке,
            # где сейчас находится скрипт
            cd ~/mrv-erp

            # Генерируем локальные переменные для создания .env (Исправлен синтаксис Bash)
            APP_VERSION=${TAG:0:7}
            APP_REPO=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')

            # Функция обновления файла env без затирки старых данных
            touch .env
            set_env() {
              local key=$1
              local val=$2
              if grep -q "^${key}=" .env; then
                sed -i "s/^${key}=.*/${key}=${val}/" .env
              else
                echo "${key}=${val}" >> .env
              fi
            }

            # Обновляем базовые переменные
            set_env "APP_REPO" "$APP_REPO"
            set_env "DOMAIN" "$DOMAIN"
            set_env "DB_PASSWORD" "$DB_PASSWORD"

            # Обновляем версии у тех сервисов, данные которых реально изменились или если запуск был ручной
            # Если приложение/сервис не был затронут, то мы оставляем ему хэш последнего коммита который на него влиял
            if [ "$UPDATE_SUPPLY" == "true" ] || [ "$IS_MANUAL" == "true" ]; then set_env "SUPPLY_VERSION" "$APP_VERSION"; fi
            if [ "$UPDATE_DIST" == "true" ] || [ "$IS_MANUAL" == "true" ]; then set_env "DISTRIBUTION_VERSION" "$APP_VERSION"; fi
            if [ "$UPDATE_FINANCE" == "true" ] || [ "$IS_MANUAL" == "true" ]; then set_env "FINANCE_VERSION" "$APP_VERSION"; fi

            chmod 600 .env

            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -af
