name: Release

on:
  push:
    branches:
      - master

# разрешаем экшену делать пуш коммитов и тегов обратно в репозиторий
permissions:
  contents: write

jobs:
  release:
    # запускаем только если это не коммит самого релиз-бота
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # fetch-depth 0 обязателен, чтобы lerna могла прочитать всю историю коммитов и тегов
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.2 # версия из package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git Bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # запуск команды релиза
      - name: Run Lerna Release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          HUSKY: 0
